anchor_version = "0.17.0"

[provider]
cluster = "devnet"
wallet = "~/openbonk-swap/wallet/keypair.json"

[programs.devnet]
serum_swap = "5paKUq27CMiotwgCh6a4GTDi4NXtGxRo3oZVyr4QXNjM"
serum_dex = { address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX", path = "./deps/serum-dex/dex/target/deploy/serum_dex.so" }

[programs.mainnet]
serum_swap = "22Y43yTVxuUkoRKdm9thyRhQ3SdgQS7c7kB6UNCiaczD"
serum_dex = { address = "srmqPvymJeFKQ4zGQed1GFppgkRHL9kaELCbyksJtPX", path = "./deps/serum-dex/dex/target/deploy/serum_dex.so" }

[[test.genesis]]
address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
program = "./deps/serum-dex/dex/target/deploy/serum_dex.so"

[scripts]
test = "mocha -t 1000000 tests/"
